Fix #12 Atualização de Tweets
parlamentaqui/etl_twitter pull request #3
Opened 2021-04-02 22:15 UTC by csafurtado

## Descrição do Pull Request:

Agora é possível popular a tabela(coleção) Tweet e buscar deputados que possuem perfis verificados no twitter com base em seu nome político

## Issue #12

## Descreva as tarefas realizadas:

- Criada rota que busca através de uma requisição para a API do Twitter os dados de usuário de um deputado (se existem e se são verificados)
- Criada rota que popula a tabela de tweets corretamente, busacando através de uma requisição para a API do Twitter os 10 tweets mais recentes de um usuário através de seu id, sendo passado neste caso os id's dos deputados que possuem perfis verificados
- Mudanças na tabela de deputados, que agora abrangem o id de sua conta no Twitter (se existe e se é verificada) e o website do político (caso ele tenha)
- Rotas adicionais para testagem foram acrescentadas
- Mudanças no .env.dev para que já venha no formato para colocar as Keys e o token posteriormente no .env

2021-04-05 12:59 UTC, gabrielalbino requested changes
Algumas mudanças bem pequenas:)

2021-04-05 12:59 UTC, gabrielalbino commented on .env.dev
> +API_KEY=
chegou a usar?

2021-04-05 12:59 UTC, gabrielalbino commented on .env.dev
> +API_KEY_SECRET=
Idem

2021-04-05 12:59 UTC, gabrielalbino commented on README.md
> +4- Rodar o comando:
Boa!

2021-04-05 12:59 UTC, gabrielalbino commented on src/api/api.py
> +                for tweet_item in Tweet.objects:
@fepas, Será que n tem um jeito mais eficiente de verificar isso? da uma olhada qnd for refatorar

2021-04-05 13:00 UTC, gabrielalbino commented on src/api/api.py
> +                for tweet_item in Tweet.objects:
Isso é pro fepas, pode ignorar cristian.

2021-04-05 13:00 UTC, gabrielalbino commented on .env.dev
> +API_KEY=
se não usou pode remover, pf

2021-04-05 13:00 UTC, gabrielalbino commented
Além do .env, favor resolver o conflito

2021-04-10 02:15 UTC, helenagoulart approved these changes

2021-04-10 02:16 UTC, helenagoulart commented
Favor arrumar conflitos :)

2021-04-15 23:15 UTC, gabrielalbino approved these changes

2021-04-15 23:15 UTC, merged